spring:
  application:
    name: catch-tripping-backend
  profiles:
    active: mysql

server:
  port: 8080
  servlet:
    session:
      timeout: 60 # 1분

logging:
  level:
    org.springframework.security: DEBUG
    com.bho.catchtrippingbackend: DEBUG
