spring:
  config:
    import:
      - classpath:config.yml
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@bonhyukouk_high?TNS_ADMIN=C:/Users/SSAFY/Downloads
    username: ${oracle.username}
    password: ${oracle.password}
  ai:
    openai:
      api-key: ${openai.api-key}

mybatis:
  mapper-locations: classpath:mapper/*.xml
