spring:
  config:
    import:
      - classpath:config.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://70.12.107.109:33061/catch_tripping?serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${mysql.username}
    password: ${mysql.password}
  ai:
    openai:
      api-key: ${openai.api-key}

mybatis:
  mapper-locations: classpath:mapper/*.xml
