spring:
  application:
    name: catch-tripping-backend
  profiles:
    active: mysql


server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: false
        http-only: true
        same-site: lax
      timeout: 1800 # 30분
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org.springframework.security: DEBUG
    com.bho.catchtrippingbackend: DEBUG

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.bho.catchtrippingbackend.**.entity